export const ADD_QUESTION = 'ADD_QUESTION';
export const CHANGE_TYPE_QUESTION = 'CHANGE_TYPE_QUESTION';
export const ADD_TEST = 'ADD_TEST';
export const ADD_TEST_NAME = 'ADD_TEST_NAME';
export const ADD_LIST_QUESTION = 'ADD_LIST_QUESTION';
export const ADD_QUESTION_INTERMEDIATE = 'ADD_QUESTION_INTERMEDIATE';
export const ADD_TEXT_QUESTION = 'ADD_TEXT_QUESTION';
export const ADD_TEXT_ANSWER = 'ADD_TEXT_ANSWER';
